version: '3.8'

services:
  fastapi-app:
    image: python:3.8
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
        uvicorn main:app --host 0.0.0.0 --port 5555"
    ports:
      - "5555:5555"
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
