version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      - N8N_SECURE_COOKIE=false
    ports:
      - "5678:5678"
    networks:
      - n8n_network
    volumes:
      - n8n_data:/home/node/.n8n

networks:
  n8n_network:
    driver: bridge

volumes:
  n8n_data:
